name = 'light_process'
version = '0.0.1'
description = 'Python multiprocessing.Process that does not need to import __main__.'
url = 'https://github.com/justengel/light_process'
author = 'Justin Engel'
author_email = 'jtengel08@gmail.com'
